services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit
    env_file: .env
    environment:
      QDRANT_URL: http://qdrant:6333
      POSTGRES_HOST: postgres
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    depends_on:
      - postgres
      - qdrant


volumes:
  postgres_data:
  qdrant_storage: